services:
  productcatalog:
    image: maven:3.9.6-eclipse-temurin-21
    volumes:
      - ./:/productcatalog
      - maven_cache:/root/.m2
    working_dir: /productcatalog
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    environment:
      - MAVEN_OPTS=-Xmx512m -Xms256m
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: productcatalog
      POSTGRES_USER: productuser
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  maven_cache:
  postgres_data: